remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: One sheet solo materials for FORGE
description: Here you can find materials that can be printed double sided to use with FORGE (Fantasy Open Roleplaying Game Engine). Primarily designed for solo play, but it can be reused as referee reference material also.
show_downloads: false
